spring.application.name=agri.smart
spring.datasource.url=jdbc:postgresql://localhost:5432/agri_smart
spring.datasource.username=postgres
spring.datasource.password=postgres2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080